#  xpm.py: -*- Python -*-  DESCRIPTIVE TEXT.

#### XPM definitions

openIcon = [
    '16 13 5 1',  
    '. c #040404',
    '# c #808304',
    'a c None',
    'b c #f3f704',     
    'c c #f3f7f3',     
    'aaaaaaaaa...aaaa',
    'aaaaaaaa.aaa.a.a',
    'aaaaaaaaaaaaa..a',
    'a...aaaaaaaa...a',
    '.bcb.......aaaaa',
    '.cbcbcbcbc.aaaaa',
    '.bcbcbcbcb.aaaaa',
    '.cbcb...........',
    '.bcb.#########.a',
    '.cb.#########.aa',
    '.b.#########.aaa',
    '..#########.aaaa',
    '...........aaaaa'
    ]

saveIcon = [
    '14 14 4 1',  
    '. c #040404',
    '# c #808304',
    'a c #bfc2bf',
    'b c None',   
    '..............',
    '.#.aaaaaaaa.a.',  
    '.#.aaaaaaaa...',  
    '.#.aaaaaaaa.#.',  
    '.#.aaaaaaaa.#.',  
    '.#.aaaaaaaa.#.',  
    '.#.aaaaaaaa.#.',  
    '.##........##.',  
    '.############.',  
    '.##.........#.',  
    '.##......aa.#.',  
    '.##......aa.#.',  
    '.##......aa.#.',  
    'b.............'   
    ]

printIcon = [
    '16 14 6 1',
    '. c #000000',
    '# c #848284',
    'a c #c6c3c6',
    'b c #ffff00',
    'c c #ffffff',
    'd c None',
    'ddddd.........dd',
    'dddd.cccccccc.dd',
    'dddd.c.....c.ddd',
    'ddd.cccccccc.ddd',
    'ddd.c.....c....d',
    'dd.cccccccc.a.a.',
    'd..........a.a..',
    '.aaaaaaaaaa.a.a.',
    '.............aa.',
    '.aaaaaa###aa.a.d',
    '.aaaaaabbbaa...d',
    '.............a.d',
    'd.aaaaaaaaa.a.dd',
    'dd...........ddd'
    ]

backIcon = [
    "16 16 5 1",
    "# c #000000",
    "a c #ffffff",
    "c c #808080",
    "b c #c0c0c0",
    ". c None",
    "................",
    ".......#........",
    "......##........",
    ".....#a#........",
    "....#aa########.",
    "...#aabaaaaaaa#.",
    "..#aabbbbbbbbb#.",
    "...#abbbbbbbbb#.",
    "...c#ab########.",
    "....c#a#ccccccc.",
    ".....c##c.......",
    "......c#c.......",
    ".......cc.......",
    "........c.......",
    "................",
    "......................"
    ]

forwardIcon = [
    "16 16 5 1",
    "# c #000000",
    "a c #ffffff",
    "c c #808080",
    "b c #c0c0c0",
    ". c None",
    "................",
    "................",
    ".........#......",
    ".........##.....",
    ".........#a#....",
    "..########aa#...",
    "..#aaaaaaabaa#..",
    "..#bbbbbbbbbaa#.",
    "..#bbbbbbbbba#..",
    "..########ba#c..",
    "..ccccccc#a#c...",
    "........c##c....",
    "........c#c.....",
    "........cc......",
    "........c.......",
    "................",
    "................"
    ]

homeIcon = [
    "16 16 4 1",
    "# c #000000",
    "a c #ffffff",
    "b c #c0c0c0",
    ". c None",
    "........... ....",
    "   ....##.......",
    "..#...####......",
    "..#..#aabb#.....",
    "..#.#aaaabb#....",
    "..##aaaaaabb#...",
    "..#aaaaaaaabb#..",
    ".#aaaaaaaaabbb#.",
    "###aaaaaaaabb###",
    "..#aaaaaaaabb#..",
    "..#aaa###aabb#..",
    "..#aaa#.#aabb#..",
    "..#aaa#.#aabb#..",
    "..#aaa#.#aabb#..",
    "..#aaa#.#aabb#..",
    "..#####.######..",
    "................"
    ]


#### the folllowing were extracted from /usr/share/gnotepad+/xpm/ ####

pasteIcon = [   
    "17 17 6 1",
    #/* colors */
    "  c None	s mask",
    ". c blue",
    "X c black	s style",
    "o c darkgray	s dark",
    "O c white	s white",
    "+ c gray	s mid",
    #/* pixels */
    "    .XXX         ",
    "    .XXX         ",
    " XXX....XXXo     ",
    "XO+XXXXXXooXo    ",
    "XO+o+o+o+ooXo    ",
    "XOo+oXXXXXXXXXX  ",
    "XO+o+XOOOOOOOOX  ",
    "XOo+oXOXXXXXXOXo ",
    "XO+o+XOOOOOOOOXo ",
    "XOo+oXOXXXXXXOXo ",
    "XO+o+XOOOOOOOOXo ",
    "XOo+oXOXXXXXXOXo ",
    "XOoooXOOOOOOOOXo ",
    " XXXXXOXXOOOOOXo ",
    "  oooXOOOOOOOOXo ",
    "     XXXXXXXXXXo ",
    "       ooooooooo "
    ]

cutIcon = [   
    "    17    17       3           1",
    #/* colors */
    "  c None	s mask",
    "n c black	s style",
    "m c darkgrey	s dark",
    #/* pixels */
    "                 ",
    "    n     nm     ",
    "    nm    nm     ",
    "     n   nm      ",
    "     nm  nm      ",
    "      n nm       ",
    "      nmnm       ",
    "       nm        ",
    "      nnnm       ",
    "    mnm  nm      ",
    "   nnnm  nnn     ",
    "  nmmnm  nm n    ",
    "  n  nm  nm nm   ",
    "  n  nm  nm nm   ",
    "   nnmm   nnm    ",
    "   mm     mm     ",
    "                 "
    ]

copyIcon = [
    "    17    17       4           1",
    #/* colors */
    "  c None	s mask",
    ". c white	s white",
    "n c black	s style",
    "m c darkgrey	s dark",
    #/* pixels */
    "                 ",
    " nnnnnnnnnn      ",
    " n........nm     ",
    " n.nnnnnnnnnnnnn ",
    " n....n........n ",
    " n.nnnn.nnnnnn.nm",
    " n....n........nm",
    " n.nnnn.nnnnnn.nm",
    " n....n........nm",
    " n.nn.n.nnnnnn.nm",
    " n....n........nm",
    " nnnnnn.nn.....nm",
    "  mmmmn........nm",
    "      nnnnnnnnnnm",
    "        mmmmmmmmm",
    "                 ",
    "                 "
]

exitIcon = [
    "17 17 4 1",
    " 	c None",
    ".	c black",
    "X	c white",
    "o	c darkred",
    "                 ",
    "       ......... ",
    "       .XXXXXX.. ",
    "       .XXXXXX.. ",
    "     ...XXXXXX.. ",
    "     .o.XXXXXX.. ",
    "......oo.XX..X.. ",
    ".oooooooo.X..X.. ",
    ".oooooooo.XXXX.. ",
    "......oo.XXXXX.. ",
    "     .o.XXXXXX.. ",
    "     ...XXXXXX.. ",
    "       .XXXX.... ",
    "       .XX...... ",
    "       ......... ",
    "                 ",
    "                 "
    ]

helpIcon = [
    "17 17 20 1",
    " 	c None",
    ".	c #000000",
    "+	c #A6BFA2",
    "@	c #F0F4EF",
    "#	c #EBF1EA",
    "$	c #E1E9E0",
    "%	c #CBDAC9",
    "&	c #F3F6F3",
    "*	c #D2DFD0",
    "=	c #C3D4C1",
    "-	c #ACC3A8",
    ";	c #BCCFB8",
    ">	c #2B2B2B",
    ",	c #E6EDE4",
    "'	c #212E1F",
    ")	c #658B5E",
    "!	c #8CAD86",
    "~	c #96B491",
    "{	c #B8CCB5",
    "]	c #8DAD88",
    "      .....      ",
    "     .+@#$%.     ",
    "    .%&@$$$*.    ",
    "   .=@-...;$->   ",
    "    .,'   .$$.   ",
    "    %.    .$-.   ",
    "         .$$).   ",
    "        .$$!.    ",
    "       .$$!.     ",
    "      .~$!.      ",
    "      .$~.       ",
    "      ....       ",
    "                 ",
    "       ..        ",
    "      .${.       ",
    "      .{].       ",
    "       ..        "
    ]

pythonIcon = [
    "    16    16       14            1",
    "  c None", 
    ". c #699328",
    "# c #686a64",
    "a c #465918",
    "b c #96c223",
    "c c #a1a39b",
    "d c #bdd867",
    "e c #cbde83",
    "f c #c2e031",
    "g c #151806",
    "h c #dce99c",
    "i c #f2f6c6",
    "j c #c5c5c1",
    "k c #946413",
    "l c #000000",
    #/* pixels */
    "llllllcgalllllll",
    "lllll#b.billllll",
    "llllligbbbilllll",
    "llll.aabk.a.llll",
    "llllffg.aia.blll",
    "llllafbba.h..lll",
    "llll.b.baidbilll",
    "lll.affbdd..llll",
    "lllfafbfgabbllll",
    "lll.f..bballllll",
    "lllfa.llllllllll",
    "lllffgllllllllll",
    "lll.b.llllllllll",
    "lllbfallllllllll",
    "lllb..llllllllll",
    "lll.bbllllllllll"
   ]

newIcon = [
    "17 17 6 1",
    "  c None	s mask",
    ". c lightgray	s light",
    "X c blue",
    "o c white	s white",
    "O c black	s style",
    "+ c darkgray	s dark",
    "        +  +o+   ",
    "        o+ +o+ o+",
    "         o+OoOo+ ",
    "OOOOOOOOOOooooO++",
    "OoooooooOoOoooooo",
    "OoooooooOooOooO++",
    "OoooooooOOOOoOo  ",
    "OooooooooooOo++o ",
    "OooooooooooOo+ +o",
    "OooooooooooO+   +",
    "OooooooooooO+    ",
    "OooooooooooO+    ",
    "OooooooooooO+    ",
    "OooooooooooO+    ",
    "OooooooooooO+    ",
    "OOOOOOOOOOOO+    ",
    "   ++++++++++    "
    ]

newwinIcon = [
    "17 17 5 1",
    "       s mask  c None",
    ".      s dark  c grey50",
    "X      s white c white",
    "x      c lightsteelblue",
    "o      s style c black",
    "         .  .X.  ",
    "         X. .X. X",
    "          X.oXoX.",
    " ooooooooooXXXXo.",
    " oxxxxxxxxXXXXXXX",
    " oxxXxxxxxoXoXXo.",
    " oxXXxxxx.xXoXoX ",
    " oxxxxxx.xxXoX..X",
    " oxxxxxxxxxXoX. .",
    " oxxxxxxxxxXo.   ",
    " oxxxxxxxxxXo.   ",
    " oxxxxxxxxxXo.   ",
    " oxxxxxxxxxXo.   ",
    " oxxxxxxxxxXo.   ",
    " oXXXXXXXXXXo.   ",
    " oooooooooooo.   ",
    "    ..........   "
    ]

closeIcon = [
    "17 17 6 1",
    #/* colors */
    " 	s None	c None",
    ".	c white",
    "X	c black",
    "o	c lightsteelblue",
    "O	c grey50",
    "x	c grey",
    #/* pixels */
    "                 ",
    "  .XXXXXXXXXXX   ",
    "  .XxxxxxxxxxX   ",
    "  .XxxxxxxxxxXO  ",
    "  .XxxxxxxxxxXO  ",
    "  .XxxxxxxxxxXO  ",
    "  .XO........XO  ",
    "  .XXXXXXXXXXXO  ",
    "  .XOOOOXOOO.XO  ",
    "  .Xoo.oXooo.XO  ",
    "  .Xo..XXXoo.XO  ",
    "  .Xoooooooo.XO  ",
    "  .Xoooooooo.XO  ",
    "  .X.........XO  ",
    "  .XXXXXXXXXXXO  ",
    "     OOOOOOOOOO  ",
    "                 "
    ]
    
helpIcon = [
    "16 16 7 1",
    " 	c None",
    ".	c #000000",
    "+	c #FFFFFF",
    "@	c #FFFF00",
    "#	c #C0C0C0",
    "$	c #000080",
    "%	c #808080",
    "  ...........   ",
    " .+++@+++@+++.  ",
    " .+@+++@+++@+.  ",
    " .+++#$$$$#++.  ",
    " .+@+$$@#$$@+.  ",
    " .+++$%++$$++.  ",
    " .+@+++@%$%@+.  ",
    " .+++@+%$#+++.  ",
    " .+@+++$%++@+.  ",
    " .+++@+++@+++.  ",
    " .+@+++$$++@+.  ",
    " .+++@+@+@+++.  ",
    "  .......++..   ",
    "         .@.    ",
    "          ..    ",
    "           .    "
    ]



bookIcon = [
    "16 16 5 1",
    #/* colors */
    ". c #000000",
    "# c #999999",
    "a c #cccccc",
    "b c #ffffff",
    "c c #c8b4c8",
    #/* pixels */
    "cca....cc....#cc",
    "..bbbbb##bbbbb..",
    "..bbbbb##bbbbb..",
    "..bbbbb##bbbbb..",
    "..bbbbb##bbbbb..",
    "..bbbbb##bbbbb..",
    "..bbbbb##bbbbb..",
    "..bbbbb##bbbbb..",
    "..bbbbb##bbbbb..",
    "..bbbbb##bbbbb..",
    "..bbbbb##bbbbb..",
    "..bbbbb##bbbbb..",
    "..bbbbb##bbbbb..",
    "..bbbbb##bbbbb..",
    "..b#...##...#b..",
    ".##############."
]

pauseIcon = [
    "17 17 3 1",
    "  c None	s mask",
    ".	c #000000",
    "+	c None   s mask",
    "+++++++++++++++++",
    "+++++++++++++++++",
    "+++++++++++++++++",
    "++++...+++...++++",
    "++++...+++...++++",
    "++++...+++...++++",
    "++++...+++...++++",
    "++++...+++...++++",
    "++++...+++...++++",
    "++++...+++...++++",
    "++++...+++...++++",
    "++++...+++...++++",
    "++++...+++...++++",
    "++++...+++...++++",
    "+++++++++++++++++",
    "+++++++++++++++++",
    "+++++++++++++++++"
    ]
